openapi: 3.0.1
info:
  title: Chat API
  version: 1.0.0
paths:
  /api/PostMessage:
    post:
      summary: Send a new chat message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                text:
                  type: string
              required:
                - name
                - text
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
  /api/GetMessages:
    get:
      summary: Get latest messages
      responses:
        '200':
          description: Array of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        text:
          type: string
        timestamp:
          type: string
          format: date-time